---
s3_object_end_point: https://rehabai.nyc3.digitaloceanspaces.com
s3_access_key: DO00Q34DACN9GH6DLCZR
s3_secret_key: mmD6CawRbl5fqmQYqh2+zTv49EutXDWJ/Nv6M3QXgwo
livekit_key: APICHaQL7Pxn7kE
livekit_secret: eH9Ize2q8RzN9ifkZfyQU0wj9OmxgDyWsQFX5umHMAvC
...